---
- name : Borrar la carpeta de sitio web
  ansible.builtin.file:
    path : /var/www/html/{{ domain }}
    state : absent
  become: yes
  become_user: root
- name: Crear directorio root de {{ cms }}
  file:
    path: /var/www/html/{{ domain }}
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  become: yes
  become_user: root
- name: Crear un index.html de prueba
  template: >
    src=index.html
    dest=/var/www/html/{{ domain }}/index.html
  become: yes
  become_user: root
- name: Crear un virtualhost
  template: >
    src=virtualhost.conf
    dest=/etc/apache2/sites-available/{{ domain }}.conf
  become: yes
  become_user: root
- name: Deshabilitar el virtualhost por defecto
  command: a2dissite 000-default.conf
  become: yes
  become_user: root
- name: Habilitar el virtualhost nuevo
  command: a2ensite {{ domain }}.conf
  become: yes
  become_user: root
  notify: restart apache
