---
    - name: Crear la carpeta de la aplicación
      file:
        path: "/var/www/html/{{ http_host }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0755'
      tags: [ apache ]
      become: yes
      become_user: root

    - name: Establecer el virtualhost de apache
      template:
        src: "files/apache.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache
      tags: [ apache ]
      become: yes
      become_user: root

    - name: Activar el módulo rewrite
      shell: /usr/sbin/a2enmod rewrite
      notify: Reload Apache
      tags: [ apache ]
      become: yes
      become_user: root

    - name: Activar el sitio nuevo
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache
      tags: [ apache ]
      become: yes
      become_user: root

    - name: Desactivar el virtualhost por defecto
      shell: /usr/sbin/a2dissite 000-default.conf
      notify: Restart Apache
      tags: [ apache ]
      become: yes
      become_user: root

  # MySQL Configuration
    # - name: Eliminar los usuarios anónimos
    #   mysql_user:
    #     name: ''
    #     host_all: yes
    #     state: absent
    #     login_user: "{{ mysql_root }}"
    #     login_password: "{{ mysql_root_password }}"
    #   tags: [ mysql ]

    # - name: Eliminar la BBDD de prueba
    #   mysql_db:
    #     name: test
    #     state: absent
    #     login_user: "{{ mysql_root }}"
    #     login_password: "{{ mysql_root_password }}"
    #   tags: [ mysql ]

    - name: Crear la base de datos de {{ cms }}
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_host : "{{ db_ip }}"
        login_user: "{{ mysql_root }}"
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: Crear el usuario de la base de datos para {{ cms }}
      mysql_user:
        name: "{{ mysql_new_user }}"
        host : "%"
        password: "{{ mysql_new_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_host : "{{ db_ip }}"
        login_user: "{{ mysql_root }}"
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

  # UFW Configuration
    - name: "UFW - Permitir el puerto {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
      tags: [ system ]
      become: yes
      become_user: root

  # WordPress Configuration
    - name: Descargar {{ cms }}
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/html/{{ http_host }}"
        remote_src: yes
        creates: "/var/www/html/{{ http_host }}/wordpress"
      tags: [ wordpress ]
      become: yes
      become_user: root

    - name: Establecer permisos de carpeta de {{ cms }}
      file:
        path: "/var/www/html/{{ http_host }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      tags: [ wordpress ]
      become: yes
      become_user: root

    - name: Establecer más permisos
      shell: "/usr/bin/find /var/www/html/{{ http_host }}/wordpress/ -type d -exec chmod 750 {} \\;"
      tags: [ wordpress ]
      become: yes
      become_user: root

    - name: Establecer permisos sobre archivos
      shell: "/usr/bin/find /var/www/html/{{ http_host }}/wordpress/ -type f -exec chmod 640 {} \\;"
      tags: [ wordpress ]
      become: yes
      become_user: root

    - name: Establecer la instalación de Wordpress
      template:
        src: "files/wp-config.php"
        dest: "/var/www/html/{{ http_host }}/wordpress/wp-config.php"
      tags: [ wordpress ]
      become: yes
      become_user: root