---
- name: Reload Apache
  service:
    name: apache2
    state: reloaded
  become: yes
  become_user: root

- name: Restart Apache
  service:
    name: apache2
    state: restarted
  become: yes
  become_user: root
